#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the deterministic StarDict fixture used by manual GUI checks."""

import argparse
import base64
import pathlib
import struct


ENTRIES = (
    (
        "example",
        '<p>UTF-8: café. <a href="bword://linked">Open linked entry</a> '
        '<img src="images/pixel.png" alt="fixture pixel"></p>',
    ),
    ("linked", "<p>Linked result.</p>"),
)

PIXEL_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUB"
    "AScY42YAAAAASUVORK5CYII="
)


def generate(output: pathlib.Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    index = bytearray()
    dictionary = bytearray()
    for headword, article in ENTRIES:
        encoded_headword = headword.encode("utf-8")
        encoded_article = article.encode("utf-8")
        index.extend(encoded_headword)
        index.append(0)
        index.extend(struct.pack(">II", len(dictionary), len(encoded_article)))
        dictionary.extend(encoded_article)

    info = (
        "StarDict's dict ifo file\n"
        "version=2.4.2\n"
        "bookname=Generated Test Dictionary\n"
        "lang_from=en\n"
        "lang_to=en\n"
        f"wordcount={len(ENTRIES)}\n"
        f"idxfilesize={len(index)}\n"
        "sametypesequence=h\n"
    )
    (output / "fixture.ifo").write_text(info, encoding="utf-8")
    (output / "fixture.idx").write_bytes(index)
    (output / "fixture.dict").write_bytes(dictionary)
    resource = output / "res" / "images" / "pixel.png"
    resource.parent.mkdir(parents=True, exist_ok=True)
    resource.write_bytes(PIXEL_PNG)
    (output / "PROVENANCE.txt").write_text(
        "Original synthetic GoldenDict test data.\n"
        "License: GPL-3.0-or-later.\n"
        "Generated by generate_fixture.py; no third-party dictionary data.\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=pathlib.Path)
    generate(parser.parse_args().output)


if __name__ == "__main__":
    main()
