#DAILY_ROLLING_MAIN配置格式：log4cplus.rootLogger=[LogLevel],appenderName1,appenderName2,...,如此处LogLevel为DEBUG，appenderName1为 DAILY_ROLLING_MAIN
log4cplus.rootLogger=DEBUG, DAILY_ROLLING_MAIN, DAILY_ROLLING_INFO

#设置日志追加到文件尾
log4cplus.appender.DAILY_ROLLING_MAIN=log4cplus::DailyRollingFileAppender
 
#设置生成日志最大个数
log4cplus.appender.DAILY_ROLLING_MAIN.MaxBackupIndex=999
log4cplus.appender.DAILY_ROLLING_MAIN.RollOnClose=true

log4cplus.appender.DAILY_ROLLING_MAIN.Locale=Chinese_China.936

#设置输出日志路径
# This property specifies rollover schedule. The possible values are MONTHLY, WEEKLY, DAILY, TWICE_DAILY, HOURLY and MINUTELY.
log4cplus.appender.DAILY_ROLLING_MAIN.Schedule=HOURLY
# When it is set true, output stream will be flushed after each appended event.
log4cplus.appender.DAILY_ROLLING_MAIN.ImmediateFlush=true
# This property specifies output file name.
log4cplus.appender.DAILY_ROLLING_MAIN.File=log/debug/debug-laser
# This property specifies filename suffix pattern to use for periodical backups of the logfile. The patern should be in format supported by log4cplus::helpers::Time::getFormatterTime(). Please notice that the format of the pattern is similar but not identical to the one used for this option in the corresponding Log4J class. If the property isn't specified a reasonable default for a given schedule type is used.
# Check sample of how to set DatePattern at the back of the file.
log4cplus.appender.DAILY_ROLLING_MAIN.DatePattern=%Y-%m-%d-%H-%M
log4cplus.appender.DAILY_ROLLING_MAIN.CreateDirs=true
log4cplus.appender.DAILY_ROLLING_MAIN.MaxHistory=60
log4cplus.appender.DAILY_ROLLING_MAIN.Append=true
 
#设置日志打印格式
log4cplus.appender.DAILY_ROLLING_MAIN.layout=log4cplus::PatternLayout
log4cplus.appender.DAILY_ROLLING_MAIN.layout.ConversionPattern=%D{%H:%M:%S.%q}  |  %m
 
#设置日志级别范围
#log4cplus.appender.DAILY_ROLLING_MAIN.filters.1=log4cplus::spi::LogLevelRangeFilter
#log4cplus.appender.DAILY_ROLLING_MAIN.filters.1.LogLevelMin=TRACE
#log4cplus.appender.DAILY_ROLLING_MAIN.filters.1.LogLevelMax=FATAL
#log4cplus.appender.DAILY_ROLLING_MAIN.filters.1.AcceptOnMatch=true
#log4cplus.appender.DAILY_ROLLING_MAIN.filters.2=log4cplus::spi::DenyAllFilter

#=====================================================================================

#设置日志追加到文件尾
log4cplus.appender.DAILY_ROLLING_INFO=log4cplus::DailyRollingFileAppender
 
#设置生成日志最大个数
log4cplus.appender.DAILY_ROLLING_INFO.MaxBackupIndex=999
log4cplus.appender.DAILY_ROLLING_INFO.RollOnClose=true

log4cplus.appender.DAILY_ROLLING_INFO.Locale=Chinese_China.936

#设置输出日志路径
# This property specifies rollover schedule. The possible values are MONTHLY, WEEKLY, DAILY, TWICE_DAILY, HOURLY and MINUTELY.
log4cplus.appender.DAILY_ROLLING_INFO.Schedule=DAILY
# When it is set true, output stream will be flushed after each appended event.
log4cplus.appender.DAILY_ROLLING_INFO.ImmediateFlush=true
# This property specifies output file name.
log4cplus.appender.DAILY_ROLLING_INFO.File=log/runtime/log-laser
# This property specifies filename suffix pattern to use for periodical backups of the logfile. The patern should be in format supported by log4cplus::helpers::Time::getFormatterTime(). Please notice that the format of the pattern is similar but not identical to the one used for this option in the corresponding Log4J class. If the property isn't specified a reasonable default for a given schedule type is used.
# Check sample of how to set DatePattern at the back of the file.
log4cplus.appender.DAILY_ROLLING_INFO.DatePattern=%Y-%m-%d-%H-%M
log4cplus.appender.DAILY_ROLLING_INFO.CreateDirs=true
log4cplus.appender.DAILY_ROLLING_INFO.MaxHistory=60
log4cplus.appender.DAILY_ROLLING_INFO.Append=true
 
#设置日志打印格式
log4cplus.appender.DAILY_ROLLING_INFO.layout=log4cplus::PatternLayout
log4cplus.appender.DAILY_ROLLING_INFO.layout.ConversionPattern=%D{%H:%M:%S.%q}  |  %m
 
#设置日志级别范围
log4cplus.appender.DAILY_ROLLING_INFO.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.DAILY_ROLLING_INFO.filters.1.LogLevelMin=INFO
log4cplus.appender.DAILY_ROLLING_INFO.filters.1.LogLevelMax=FATAL
log4cplus.appender.DAILY_ROLLING_INFO.filters.1.AcceptOnMatch=true
#log4cplus.appender.DAILY_ROLLING_INFO.filters.2=log4cplus::spi::DenyAllFilter

#=====================================================================================
log4cplus.logger.error=ERROR, DAILY_ROLLING_ERROR

#设置日志追加到文件尾
log4cplus.appender.DAILY_ROLLING_ERROR=log4cplus::DailyRollingFileAppender
 
#设置生成日志最大个数
log4cplus.appender.DAILY_ROLLING_ERROR.MaxBackupIndex=999
log4cplus.appender.DAILY_ROLLING_ERROR.RollOnClose=false

log4cplus.appender.DAILY_ROLLING_ERROR.Locale=Chinese_China.936

#设置输出日志路径
# This property specifies rollover schedule. The possible values are MONTHLY, WEEKLY, DAILY, TWICE_DAILY, HOURLY and MINUTELY.
log4cplus.appender.DAILY_ROLLING_ERROR.Schedule=HOURLY
# When it is set true, output stream will be flushed after each appended event.
log4cplus.appender.DAILY_ROLLING_ERROR.ImmediateFlush=true
# This property specifies output file name.
log4cplus.appender.DAILY_ROLLING_ERROR.File=log/error/error-laser
# This property specifies filename suffix pattern to use for periodical backups of the logfile. The patern should be in format supported by log4cplus::helpers::Time::getFormatterTime(). Please notice that the format of the pattern is similar but not identical to the one used for this option in the corresponding Log4J class. If the property isn't specified a reasonable default for a given schedule type is used.
# Check sample of how to set DatePattern at the back of the file.
log4cplus.appender.DAILY_ROLLING_ERROR.DatePattern=%Y-%m-%d-%H-%M
log4cplus.appender.DAILY_ROLLING_ERROR.CreateDirs=true
log4cplus.appender.DAILY_ROLLING_ERROR.MaxHistory=60
log4cplus.appender.DAILY_ROLLING_ERROR.Append=true
 
#设置日志打印格式
log4cplus.appender.DAILY_ROLLING_ERROR.layout=log4cplus::PatternLayout
log4cplus.appender.DAILY_ROLLING_ERROR.layout.ConversionPattern=%D{%H:%M:%S.%q}  |  %m
 
#设置日志级别范围

# Sample of setting date and time in "DatePattern"
	#	%a	Weekday as locale’s abbreviated name.	Mon
	#	%A	Weekday as locale’s full name.	Monday
	#	%w	Weekday as a decimal number, where 0 is Sunday and 6 is Saturday.	1
	#	%d	Day of the month as a zero-padded decimal number.	30
	#	%-d	Day of the month as a decimal number. (Platform specific)	30
	#	%b	Month as locale’s abbreviated name.	Sep
	#	%B	Month as locale’s full name.	September
	#	%m	Month as a zero-padded decimal number.	09
	#	%-m	Month as a decimal number. (Platform specific)	9
	#	%y	Year without century as a zero-padded decimal number.	13
	#	%Y	Year with century as a decimal number.	2013
	#	%H	Hour (24-hour clock) as a zero-padded decimal number.	07
	#	%-H	Hour (24-hour clock) as a decimal number. (Platform specific)	7
	#	%I	Hour (12-hour clock) as a zero-padded decimal number.	07
	#	%-I	Hour (12-hour clock) as a decimal number. (Platform specific)	7
	#	%p	Locale’s equivalent of either AM or PM.	AM
	#	%M	Minute as a zero-padded decimal number.	06
	#	%-M	Minute as a decimal number. (Platform specific)	6
	#	%S	Second as a zero-padded decimal number.	05
	#	%-S	Second as a decimal number. (Platform specific)	5