// AUTOGENERATED, DO NOT EDIT

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSE
#  define TI_TRY_SSE 1
#  define TI_CPU_FORCE_SSE 1
#  define TI_CPU_HAS_SUPPORT_SSE 1
#  define TI_CPU_CALL_SSE(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSE_(fn, args) return (opt_SSE::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSE
#  define TI_TRY_SSE 1
#  define TI_CPU_FORCE_SSE 0
#  define TI_CPU_HAS_SUPPORT_SSE (ti::checkHardwareSupport(TI_CPU_SSE))
#  define TI_CPU_CALL_SSE(fn, args) if (TI_CPU_HAS_SUPPORT_SSE) return (opt_SSE::fn args)
#  define TI_CPU_CALL_SSE_(fn, args) if (TI_CPU_HAS_SUPPORT_SSE) return (opt_SSE::fn args)
#else
#  define TI_TRY_SSE 0
#  define TI_CPU_FORCE_SSE 0
#  define TI_CPU_HAS_SUPPORT_SSE 0
#  define TI_CPU_CALL_SSE(fn, args)
#  define TI_CPU_CALL_SSE_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSE(fn, args, mode, ...)  TI_CPU_CALL_SSE(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSE2
#  define TI_TRY_SSE2 1
#  define TI_CPU_FORCE_SSE2 1
#  define TI_CPU_HAS_SUPPORT_SSE2 1
#  define TI_CPU_CALL_SSE2(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSE2_(fn, args) return (opt_SSE2::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSE2
#  define TI_TRY_SSE2 1
#  define TI_CPU_FORCE_SSE2 0
#  define TI_CPU_HAS_SUPPORT_SSE2 (ti::checkHardwareSupport(TI_CPU_SSE2))
#  define TI_CPU_CALL_SSE2(fn, args) if (TI_CPU_HAS_SUPPORT_SSE2) return (opt_SSE2::fn args)
#  define TI_CPU_CALL_SSE2_(fn, args) if (TI_CPU_HAS_SUPPORT_SSE2) return (opt_SSE2::fn args)
#else
#  define TI_TRY_SSE2 0
#  define TI_CPU_FORCE_SSE2 0
#  define TI_CPU_HAS_SUPPORT_SSE2 0
#  define TI_CPU_CALL_SSE2(fn, args)
#  define TI_CPU_CALL_SSE2_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSE2(fn, args, mode, ...)  TI_CPU_CALL_SSE2(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSE3
#  define TI_TRY_SSE3 1
#  define TI_CPU_FORCE_SSE3 1
#  define TI_CPU_HAS_SUPPORT_SSE3 1
#  define TI_CPU_CALL_SSE3(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSE3_(fn, args) return (opt_SSE3::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSE3
#  define TI_TRY_SSE3 1
#  define TI_CPU_FORCE_SSE3 0
#  define TI_CPU_HAS_SUPPORT_SSE3 (ti::checkHardwareSupport(TI_CPU_SSE3))
#  define TI_CPU_CALL_SSE3(fn, args) if (TI_CPU_HAS_SUPPORT_SSE3) return (opt_SSE3::fn args)
#  define TI_CPU_CALL_SSE3_(fn, args) if (TI_CPU_HAS_SUPPORT_SSE3) return (opt_SSE3::fn args)
#else
#  define TI_TRY_SSE3 0
#  define TI_CPU_FORCE_SSE3 0
#  define TI_CPU_HAS_SUPPORT_SSE3 0
#  define TI_CPU_CALL_SSE3(fn, args)
#  define TI_CPU_CALL_SSE3_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSE3(fn, args, mode, ...)  TI_CPU_CALL_SSE3(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSSE3
#  define TI_TRY_SSSE3 1
#  define TI_CPU_FORCE_SSSE3 1
#  define TI_CPU_HAS_SUPPORT_SSSE3 1
#  define TI_CPU_CALL_SSSE3(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSSE3_(fn, args) return (opt_SSSE3::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSSE3
#  define TI_TRY_SSSE3 1
#  define TI_CPU_FORCE_SSSE3 0
#  define TI_CPU_HAS_SUPPORT_SSSE3 (ti::checkHardwareSupport(TI_CPU_SSSE3))
#  define TI_CPU_CALL_SSSE3(fn, args) if (TI_CPU_HAS_SUPPORT_SSSE3) return (opt_SSSE3::fn args)
#  define TI_CPU_CALL_SSSE3_(fn, args) if (TI_CPU_HAS_SUPPORT_SSSE3) return (opt_SSSE3::fn args)
#else
#  define TI_TRY_SSSE3 0
#  define TI_CPU_FORCE_SSSE3 0
#  define TI_CPU_HAS_SUPPORT_SSSE3 0
#  define TI_CPU_CALL_SSSE3(fn, args)
#  define TI_CPU_CALL_SSSE3_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSSE3(fn, args, mode, ...)  TI_CPU_CALL_SSSE3(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSE4_1
#  define TI_TRY_SSE4_1 1
#  define TI_CPU_FORCE_SSE4_1 1
#  define TI_CPU_HAS_SUPPORT_SSE4_1 1
#  define TI_CPU_CALL_SSE4_1(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSE4_1_(fn, args) return (opt_SSE4_1::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSE4_1
#  define TI_TRY_SSE4_1 1
#  define TI_CPU_FORCE_SSE4_1 0
#  define TI_CPU_HAS_SUPPORT_SSE4_1 (ti::checkHardwareSupport(TI_CPU_SSE4_1))
#  define TI_CPU_CALL_SSE4_1(fn, args) if (TI_CPU_HAS_SUPPORT_SSE4_1) return (opt_SSE4_1::fn args)
#  define TI_CPU_CALL_SSE4_1_(fn, args) if (TI_CPU_HAS_SUPPORT_SSE4_1) return (opt_SSE4_1::fn args)
#else
#  define TI_TRY_SSE4_1 0
#  define TI_CPU_FORCE_SSE4_1 0
#  define TI_CPU_HAS_SUPPORT_SSE4_1 0
#  define TI_CPU_CALL_SSE4_1(fn, args)
#  define TI_CPU_CALL_SSE4_1_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSE4_1(fn, args, mode, ...)  TI_CPU_CALL_SSE4_1(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_SSE4_2
#  define TI_TRY_SSE4_2 1
#  define TI_CPU_FORCE_SSE4_2 1
#  define TI_CPU_HAS_SUPPORT_SSE4_2 1
#  define TI_CPU_CALL_SSE4_2(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_SSE4_2_(fn, args) return (opt_SSE4_2::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_SSE4_2
#  define TI_TRY_SSE4_2 1
#  define TI_CPU_FORCE_SSE4_2 0
#  define TI_CPU_HAS_SUPPORT_SSE4_2 (ti::checkHardwareSupport(TI_CPU_SSE4_2))
#  define TI_CPU_CALL_SSE4_2(fn, args) if (TI_CPU_HAS_SUPPORT_SSE4_2) return (opt_SSE4_2::fn args)
#  define TI_CPU_CALL_SSE4_2_(fn, args) if (TI_CPU_HAS_SUPPORT_SSE4_2) return (opt_SSE4_2::fn args)
#else
#  define TI_TRY_SSE4_2 0
#  define TI_CPU_FORCE_SSE4_2 0
#  define TI_CPU_HAS_SUPPORT_SSE4_2 0
#  define TI_CPU_CALL_SSE4_2(fn, args)
#  define TI_CPU_CALL_SSE4_2_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_SSE4_2(fn, args, mode, ...)  TI_CPU_CALL_SSE4_2(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_POPCNT
#  define TI_TRY_POPCNT 1
#  define TI_CPU_FORCE_POPCNT 1
#  define TI_CPU_HAS_SUPPORT_POPCNT 1
#  define TI_CPU_CALL_POPCNT(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_POPCNT_(fn, args) return (opt_POPCNT::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_POPCNT
#  define TI_TRY_POPCNT 1
#  define TI_CPU_FORCE_POPCNT 0
#  define TI_CPU_HAS_SUPPORT_POPCNT (ti::checkHardwareSupport(TI_CPU_POPCNT))
#  define TI_CPU_CALL_POPCNT(fn, args) if (TI_CPU_HAS_SUPPORT_POPCNT) return (opt_POPCNT::fn args)
#  define TI_CPU_CALL_POPCNT_(fn, args) if (TI_CPU_HAS_SUPPORT_POPCNT) return (opt_POPCNT::fn args)
#else
#  define TI_TRY_POPCNT 0
#  define TI_CPU_FORCE_POPCNT 0
#  define TI_CPU_HAS_SUPPORT_POPCNT 0
#  define TI_CPU_CALL_POPCNT(fn, args)
#  define TI_CPU_CALL_POPCNT_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_POPCNT(fn, args, mode, ...)  TI_CPU_CALL_POPCNT(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX
#  define TI_TRY_AVX 1
#  define TI_CPU_FORCE_AVX 1
#  define TI_CPU_HAS_SUPPORT_AVX 1
#  define TI_CPU_CALL_AVX(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX_(fn, args) return (opt_AVX::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX
#  define TI_TRY_AVX 1
#  define TI_CPU_FORCE_AVX 0
#  define TI_CPU_HAS_SUPPORT_AVX (ti::checkHardwareSupport(TI_CPU_AVX))
#  define TI_CPU_CALL_AVX(fn, args) if (TI_CPU_HAS_SUPPORT_AVX) return (opt_AVX::fn args)
#  define TI_CPU_CALL_AVX_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX) return (opt_AVX::fn args)
#else
#  define TI_TRY_AVX 0
#  define TI_CPU_FORCE_AVX 0
#  define TI_CPU_HAS_SUPPORT_AVX 0
#  define TI_CPU_CALL_AVX(fn, args)
#  define TI_CPU_CALL_AVX_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX(fn, args, mode, ...)  TI_CPU_CALL_AVX(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_FP16
#  define TI_TRY_FP16 1
#  define TI_CPU_FORCE_FP16 1
#  define TI_CPU_HAS_SUPPORT_FP16 1
#  define TI_CPU_CALL_FP16(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_FP16_(fn, args) return (opt_FP16::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_FP16
#  define TI_TRY_FP16 1
#  define TI_CPU_FORCE_FP16 0
#  define TI_CPU_HAS_SUPPORT_FP16 (ti::checkHardwareSupport(TI_CPU_FP16))
#  define TI_CPU_CALL_FP16(fn, args) if (TI_CPU_HAS_SUPPORT_FP16) return (opt_FP16::fn args)
#  define TI_CPU_CALL_FP16_(fn, args) if (TI_CPU_HAS_SUPPORT_FP16) return (opt_FP16::fn args)
#else
#  define TI_TRY_FP16 0
#  define TI_CPU_FORCE_FP16 0
#  define TI_CPU_HAS_SUPPORT_FP16 0
#  define TI_CPU_CALL_FP16(fn, args)
#  define TI_CPU_CALL_FP16_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_FP16(fn, args, mode, ...)  TI_CPU_CALL_FP16(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX2
#  define TI_TRY_AVX2 1
#  define TI_CPU_FORCE_AVX2 1
#  define TI_CPU_HAS_SUPPORT_AVX2 1
#  define TI_CPU_CALL_AVX2(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX2_(fn, args) return (opt_AVX2::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX2
#  define TI_TRY_AVX2 1
#  define TI_CPU_FORCE_AVX2 0
#  define TI_CPU_HAS_SUPPORT_AVX2 (ti::checkHardwareSupport(TI_CPU_AVX2))
#  define TI_CPU_CALL_AVX2(fn, args) if (TI_CPU_HAS_SUPPORT_AVX2) return (opt_AVX2::fn args)
#  define TI_CPU_CALL_AVX2_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX2) return (opt_AVX2::fn args)
#else
#  define TI_TRY_AVX2 0
#  define TI_CPU_FORCE_AVX2 0
#  define TI_CPU_HAS_SUPPORT_AVX2 0
#  define TI_CPU_CALL_AVX2(fn, args)
#  define TI_CPU_CALL_AVX2_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX2(fn, args, mode, ...)  TI_CPU_CALL_AVX2(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_FMA3
#  define TI_TRY_FMA3 1
#  define TI_CPU_FORCE_FMA3 1
#  define TI_CPU_HAS_SUPPORT_FMA3 1
#  define TI_CPU_CALL_FMA3(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_FMA3_(fn, args) return (opt_FMA3::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_FMA3
#  define TI_TRY_FMA3 1
#  define TI_CPU_FORCE_FMA3 0
#  define TI_CPU_HAS_SUPPORT_FMA3 (ti::checkHardwareSupport(TI_CPU_FMA3))
#  define TI_CPU_CALL_FMA3(fn, args) if (TI_CPU_HAS_SUPPORT_FMA3) return (opt_FMA3::fn args)
#  define TI_CPU_CALL_FMA3_(fn, args) if (TI_CPU_HAS_SUPPORT_FMA3) return (opt_FMA3::fn args)
#else
#  define TI_TRY_FMA3 0
#  define TI_CPU_FORCE_FMA3 0
#  define TI_CPU_HAS_SUPPORT_FMA3 0
#  define TI_CPU_CALL_FMA3(fn, args)
#  define TI_CPU_CALL_FMA3_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_FMA3(fn, args, mode, ...)  TI_CPU_CALL_FMA3(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX_512F
#  define TI_TRY_AVX_512F 1
#  define TI_CPU_FORCE_AVX_512F 1
#  define TI_CPU_HAS_SUPPORT_AVX_512F 1
#  define TI_CPU_CALL_AVX_512F(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX_512F_(fn, args) return (opt_AVX_512F::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX_512F
#  define TI_TRY_AVX_512F 1
#  define TI_CPU_FORCE_AVX_512F 0
#  define TI_CPU_HAS_SUPPORT_AVX_512F (ti::checkHardwareSupport(TI_CPU_AVX_512F))
#  define TI_CPU_CALL_AVX_512F(fn, args) if (TI_CPU_HAS_SUPPORT_AVX_512F) return (opt_AVX_512F::fn args)
#  define TI_CPU_CALL_AVX_512F_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX_512F) return (opt_AVX_512F::fn args)
#else
#  define TI_TRY_AVX_512F 0
#  define TI_CPU_FORCE_AVX_512F 0
#  define TI_CPU_HAS_SUPPORT_AVX_512F 0
#  define TI_CPU_CALL_AVX_512F(fn, args)
#  define TI_CPU_CALL_AVX_512F_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX_512F(fn, args, mode, ...)  TI_CPU_CALL_AVX_512F(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_COMMON
#  define TI_TRY_AVX512_COMMON 1
#  define TI_CPU_FORCE_AVX512_COMMON 1
#  define TI_CPU_HAS_SUPPORT_AVX512_COMMON 1
#  define TI_CPU_CALL_AVX512_COMMON(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_COMMON_(fn, args) return (opt_AVX512_COMMON::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_COMMON
#  define TI_TRY_AVX512_COMMON 1
#  define TI_CPU_FORCE_AVX512_COMMON 0
#  define TI_CPU_HAS_SUPPORT_AVX512_COMMON (ti::checkHardwareSupport(TI_CPU_AVX512_COMMON))
#  define TI_CPU_CALL_AVX512_COMMON(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_COMMON) return (opt_AVX512_COMMON::fn args)
#  define TI_CPU_CALL_AVX512_COMMON_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_COMMON) return (opt_AVX512_COMMON::fn args)
#else
#  define TI_TRY_AVX512_COMMON 0
#  define TI_CPU_FORCE_AVX512_COMMON 0
#  define TI_CPU_HAS_SUPPORT_AVX512_COMMON 0
#  define TI_CPU_CALL_AVX512_COMMON(fn, args)
#  define TI_CPU_CALL_AVX512_COMMON_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_COMMON(fn, args, mode, ...)  TI_CPU_CALL_AVX512_COMMON(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_KNL
#  define TI_TRY_AVX512_KNL 1
#  define TI_CPU_FORCE_AVX512_KNL 1
#  define TI_CPU_HAS_SUPPORT_AVX512_KNL 1
#  define TI_CPU_CALL_AVX512_KNL(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_KNL_(fn, args) return (opt_AVX512_KNL::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_KNL
#  define TI_TRY_AVX512_KNL 1
#  define TI_CPU_FORCE_AVX512_KNL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_KNL (ti::checkHardwareSupport(TI_CPU_AVX512_KNL))
#  define TI_CPU_CALL_AVX512_KNL(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_KNL) return (opt_AVX512_KNL::fn args)
#  define TI_CPU_CALL_AVX512_KNL_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_KNL) return (opt_AVX512_KNL::fn args)
#else
#  define TI_TRY_AVX512_KNL 0
#  define TI_CPU_FORCE_AVX512_KNL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_KNL 0
#  define TI_CPU_CALL_AVX512_KNL(fn, args)
#  define TI_CPU_CALL_AVX512_KNL_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_KNL(fn, args, mode, ...)  TI_CPU_CALL_AVX512_KNL(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_KNM
#  define TI_TRY_AVX512_KNM 1
#  define TI_CPU_FORCE_AVX512_KNM 1
#  define TI_CPU_HAS_SUPPORT_AVX512_KNM 1
#  define TI_CPU_CALL_AVX512_KNM(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_KNM_(fn, args) return (opt_AVX512_KNM::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_KNM
#  define TI_TRY_AVX512_KNM 1
#  define TI_CPU_FORCE_AVX512_KNM 0
#  define TI_CPU_HAS_SUPPORT_AVX512_KNM (ti::checkHardwareSupport(TI_CPU_AVX512_KNM))
#  define TI_CPU_CALL_AVX512_KNM(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_KNM) return (opt_AVX512_KNM::fn args)
#  define TI_CPU_CALL_AVX512_KNM_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_KNM) return (opt_AVX512_KNM::fn args)
#else
#  define TI_TRY_AVX512_KNM 0
#  define TI_CPU_FORCE_AVX512_KNM 0
#  define TI_CPU_HAS_SUPPORT_AVX512_KNM 0
#  define TI_CPU_CALL_AVX512_KNM(fn, args)
#  define TI_CPU_CALL_AVX512_KNM_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_KNM(fn, args, mode, ...)  TI_CPU_CALL_AVX512_KNM(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_SKX
#  define TI_TRY_AVX512_SKX 1
#  define TI_CPU_FORCE_AVX512_SKX 1
#  define TI_CPU_HAS_SUPPORT_AVX512_SKX 1
#  define TI_CPU_CALL_AVX512_SKX(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_SKX_(fn, args) return (opt_AVX512_SKX::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_SKX
#  define TI_TRY_AVX512_SKX 1
#  define TI_CPU_FORCE_AVX512_SKX 0
#  define TI_CPU_HAS_SUPPORT_AVX512_SKX (ti::checkHardwareSupport(TI_CPU_AVX512_SKX))
#  define TI_CPU_CALL_AVX512_SKX(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_SKX) return (opt_AVX512_SKX::fn args)
#  define TI_CPU_CALL_AVX512_SKX_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_SKX) return (opt_AVX512_SKX::fn args)
#else
#  define TI_TRY_AVX512_SKX 0
#  define TI_CPU_FORCE_AVX512_SKX 0
#  define TI_CPU_HAS_SUPPORT_AVX512_SKX 0
#  define TI_CPU_CALL_AVX512_SKX(fn, args)
#  define TI_CPU_CALL_AVX512_SKX_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_SKX(fn, args, mode, ...)  TI_CPU_CALL_AVX512_SKX(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_CNL
#  define TI_TRY_AVX512_CNL 1
#  define TI_CPU_FORCE_AVX512_CNL 1
#  define TI_CPU_HAS_SUPPORT_AVX512_CNL 1
#  define TI_CPU_CALL_AVX512_CNL(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_CNL_(fn, args) return (opt_AVX512_CNL::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_CNL
#  define TI_TRY_AVX512_CNL 1
#  define TI_CPU_FORCE_AVX512_CNL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_CNL (ti::checkHardwareSupport(TI_CPU_AVX512_CNL))
#  define TI_CPU_CALL_AVX512_CNL(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_CNL) return (opt_AVX512_CNL::fn args)
#  define TI_CPU_CALL_AVX512_CNL_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_CNL) return (opt_AVX512_CNL::fn args)
#else
#  define TI_TRY_AVX512_CNL 0
#  define TI_CPU_FORCE_AVX512_CNL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_CNL 0
#  define TI_CPU_CALL_AVX512_CNL(fn, args)
#  define TI_CPU_CALL_AVX512_CNL_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_CNL(fn, args, mode, ...)  TI_CPU_CALL_AVX512_CNL(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_CLX
#  define TI_TRY_AVX512_CLX 1
#  define TI_CPU_FORCE_AVX512_CLX 1
#  define TI_CPU_HAS_SUPPORT_AVX512_CLX 1
#  define TI_CPU_CALL_AVX512_CLX(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_CLX_(fn, args) return (opt_AVX512_CLX::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_CLX
#  define TI_TRY_AVX512_CLX 1
#  define TI_CPU_FORCE_AVX512_CLX 0
#  define TI_CPU_HAS_SUPPORT_AVX512_CLX (ti::checkHardwareSupport(TI_CPU_AVX512_CLX))
#  define TI_CPU_CALL_AVX512_CLX(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_CLX) return (opt_AVX512_CLX::fn args)
#  define TI_CPU_CALL_AVX512_CLX_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_CLX) return (opt_AVX512_CLX::fn args)
#else
#  define TI_TRY_AVX512_CLX 0
#  define TI_CPU_FORCE_AVX512_CLX 0
#  define TI_CPU_HAS_SUPPORT_AVX512_CLX 0
#  define TI_CPU_CALL_AVX512_CLX(fn, args)
#  define TI_CPU_CALL_AVX512_CLX_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_CLX(fn, args, mode, ...)  TI_CPU_CALL_AVX512_CLX(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_AVX512_ICL
#  define TI_TRY_AVX512_ICL 1
#  define TI_CPU_FORCE_AVX512_ICL 1
#  define TI_CPU_HAS_SUPPORT_AVX512_ICL 1
#  define TI_CPU_CALL_AVX512_ICL(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_AVX512_ICL_(fn, args) return (opt_AVX512_ICL::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_AVX512_ICL
#  define TI_TRY_AVX512_ICL 1
#  define TI_CPU_FORCE_AVX512_ICL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_ICL (ti::checkHardwareSupport(TI_CPU_AVX512_ICL))
#  define TI_CPU_CALL_AVX512_ICL(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_ICL) return (opt_AVX512_ICL::fn args)
#  define TI_CPU_CALL_AVX512_ICL_(fn, args) if (TI_CPU_HAS_SUPPORT_AVX512_ICL) return (opt_AVX512_ICL::fn args)
#else
#  define TI_TRY_AVX512_ICL 0
#  define TI_CPU_FORCE_AVX512_ICL 0
#  define TI_CPU_HAS_SUPPORT_AVX512_ICL 0
#  define TI_CPU_CALL_AVX512_ICL(fn, args)
#  define TI_CPU_CALL_AVX512_ICL_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_AVX512_ICL(fn, args, mode, ...)  TI_CPU_CALL_AVX512_ICL(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_NEON
#  define TI_TRY_NEON 1
#  define TI_CPU_FORCE_NEON 1
#  define TI_CPU_HAS_SUPPORT_NEON 1
#  define TI_CPU_CALL_NEON(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_NEON_(fn, args) return (opt_NEON::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_NEON
#  define TI_TRY_NEON 1
#  define TI_CPU_FORCE_NEON 0
#  define TI_CPU_HAS_SUPPORT_NEON (ti::checkHardwareSupport(TI_CPU_NEON))
#  define TI_CPU_CALL_NEON(fn, args) if (TI_CPU_HAS_SUPPORT_NEON) return (opt_NEON::fn args)
#  define TI_CPU_CALL_NEON_(fn, args) if (TI_CPU_HAS_SUPPORT_NEON) return (opt_NEON::fn args)
#else
#  define TI_TRY_NEON 0
#  define TI_CPU_FORCE_NEON 0
#  define TI_CPU_HAS_SUPPORT_NEON 0
#  define TI_CPU_CALL_NEON(fn, args)
#  define TI_CPU_CALL_NEON_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_NEON(fn, args, mode, ...)  TI_CPU_CALL_NEON(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_MSA
#  define TI_TRY_MSA 1
#  define TI_CPU_FORCE_MSA 1
#  define TI_CPU_HAS_SUPPORT_MSA 1
#  define TI_CPU_CALL_MSA(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_MSA_(fn, args) return (opt_MSA::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_MSA
#  define TI_TRY_MSA 1
#  define TI_CPU_FORCE_MSA 0
#  define TI_CPU_HAS_SUPPORT_MSA (ti::checkHardwareSupport(TI_CPU_MSA))
#  define TI_CPU_CALL_MSA(fn, args) if (TI_CPU_HAS_SUPPORT_MSA) return (opt_MSA::fn args)
#  define TI_CPU_CALL_MSA_(fn, args) if (TI_CPU_HAS_SUPPORT_MSA) return (opt_MSA::fn args)
#else
#  define TI_TRY_MSA 0
#  define TI_CPU_FORCE_MSA 0
#  define TI_CPU_HAS_SUPPORT_MSA 0
#  define TI_CPU_CALL_MSA(fn, args)
#  define TI_CPU_CALL_MSA_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_MSA(fn, args, mode, ...)  TI_CPU_CALL_MSA(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_VSX
#  define TI_TRY_VSX 1
#  define TI_CPU_FORCE_VSX 1
#  define TI_CPU_HAS_SUPPORT_VSX 1
#  define TI_CPU_CALL_VSX(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_VSX_(fn, args) return (opt_VSX::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_VSX
#  define TI_TRY_VSX 1
#  define TI_CPU_FORCE_VSX 0
#  define TI_CPU_HAS_SUPPORT_VSX (ti::checkHardwareSupport(TI_CPU_VSX))
#  define TI_CPU_CALL_VSX(fn, args) if (TI_CPU_HAS_SUPPORT_VSX) return (opt_VSX::fn args)
#  define TI_CPU_CALL_VSX_(fn, args) if (TI_CPU_HAS_SUPPORT_VSX) return (opt_VSX::fn args)
#else
#  define TI_TRY_VSX 0
#  define TI_CPU_FORCE_VSX 0
#  define TI_CPU_HAS_SUPPORT_VSX 0
#  define TI_CPU_CALL_VSX(fn, args)
#  define TI_CPU_CALL_VSX_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_VSX(fn, args, mode, ...)  TI_CPU_CALL_VSX(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_VSX3
#  define TI_TRY_VSX3 1
#  define TI_CPU_FORCE_VSX3 1
#  define TI_CPU_HAS_SUPPORT_VSX3 1
#  define TI_CPU_CALL_VSX3(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_VSX3_(fn, args) return (opt_VSX3::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_VSX3
#  define TI_TRY_VSX3 1
#  define TI_CPU_FORCE_VSX3 0
#  define TI_CPU_HAS_SUPPORT_VSX3 (ti::checkHardwareSupport(TI_CPU_VSX3))
#  define TI_CPU_CALL_VSX3(fn, args) if (TI_CPU_HAS_SUPPORT_VSX3) return (opt_VSX3::fn args)
#  define TI_CPU_CALL_VSX3_(fn, args) if (TI_CPU_HAS_SUPPORT_VSX3) return (opt_VSX3::fn args)
#else
#  define TI_TRY_VSX3 0
#  define TI_CPU_FORCE_VSX3 0
#  define TI_CPU_HAS_SUPPORT_VSX3 0
#  define TI_CPU_CALL_VSX3(fn, args)
#  define TI_CPU_CALL_VSX3_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_VSX3(fn, args, mode, ...)  TI_CPU_CALL_VSX3(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#if !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_COMPILE_RVV
#  define TI_TRY_RVV 1
#  define TI_CPU_FORCE_RVV 1
#  define TI_CPU_HAS_SUPPORT_RVV 1
#  define TI_CPU_CALL_RVV(fn, args) return (cpu_baseline::fn args)
#  define TI_CPU_CALL_RVV_(fn, args) return (opt_RVV::fn args)
#elif !defined TI_DISABLE_OPTIMIZATION && defined TI_ENABLE_INTRINSICS && defined TI_CPU_DISPATCH_COMPILE_RVV
#  define TI_TRY_RVV 1
#  define TI_CPU_FORCE_RVV 0
#  define TI_CPU_HAS_SUPPORT_RVV (ti::checkHardwareSupport(TI_CPU_RVV))
#  define TI_CPU_CALL_RVV(fn, args) if (TI_CPU_HAS_SUPPORT_RVV) return (opt_RVV::fn args)
#  define TI_CPU_CALL_RVV_(fn, args) if (TI_CPU_HAS_SUPPORT_RVV) return (opt_RVV::fn args)
#else
#  define TI_TRY_RVV 0
#  define TI_CPU_FORCE_RVV 0
#  define TI_CPU_HAS_SUPPORT_RVV 0
#  define TI_CPU_CALL_RVV(fn, args)
#  define TI_CPU_CALL_RVV_(fn, args)
#endif
#define __TI_CPU_DISPATCH_CHAIN_RVV(fn, args, mode, ...)  TI_CPU_CALL_RVV(fn, args); __TI_EXPAND(__TI_CPU_DISPATCH_CHAIN_ ## mode(fn, args, __VA_ARGS__))

#define TI_CPU_CALL_BASELINE(fn, args) return (cpu_baseline::fn args)
#define __TI_CPU_DISPATCH_CHAIN_BASELINE(fn, args, mode, ...)  TI_CPU_CALL_BASELINE(fn, args) /* last in sequence */
