# W3.1 covers one family; other legacy tests receive no new exemption.
function(gd_check_full_text_scope_isolation root_target)
  set(pending "${root_target}")
  set(visited "")
  set(report "")
  while(pending)
    list(POP_FRONT pending current)
    if(current IN_LIST visited OR NOT TARGET "${current}")
      continue()
    endif()
    list(APPEND visited "${current}")
    if(current STREQUAL "full_text_dictionary_scope_test")
      message(FATAL_ERROR "W3.1 isolation violation: ${root_target} depends on the full-text scope test runner")
    endif()
    foreach(property SOURCES INTERFACE_SOURCES LINK_LIBRARIES INTERFACE_LINK_LIBRARIES MANUALLY_ADDED_DEPENDENCIES)
      get_target_property(values "${current}" "${property}")
      if(NOT values)
        continue()
      endif()
      string(APPEND report "${current} ${property}: ${values}\n")
      foreach(value IN LISTS values)
        if(value MATCHES "full_text_dictionary_scope_(test|test_access)\\.(cpp|cc|h)" OR
           value MATCHES "full_text_dictionary_scope_test")
          message(FATAL_ERROR "W3.1 isolation violation: ${current} ${property} contains ${value}")
        endif()
        # Check both alternatives of conditional link/object expressions.
        string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_.+-]*(::[A-Za-z_][A-Za-z0-9_.+-]*)*" tokens "${value}")
        foreach(token IN LISTS tokens)
          if(TARGET "${token}")
            list(APPEND pending "${token}")
          endif()
        endforeach()
      endforeach()
    endforeach()
  endwhile()
  file(WRITE "${CMAKE_BINARY_DIR}/full-text-scope-production-closure.txt" "${report}")
endfunction()
