#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate a bounded Aard corpus whose full-text work can be cancelled."""

from __future__ import annotations

import argparse
import json
import os
import struct
import tempfile
import zlib
from collections.abc import Iterable
from pathlib import Path

DISPOSABLE_MARKER = ".goldendict-disposable-acceptance-v1"
MARKER_CONTENT = "Generated disposable GoldenDict acceptance corpus.\n"
DEFAULT_ENTRY_COUNT = 100_000
MAX_ENTRY_COUNT = 100_000
MAX_FIXTURE_BYTES = 64 * 1024 * 1024
ARTICLE_TEXT_BYTES = 1_024


class FixtureError(RuntimeError):
    """Raised when a safe deterministic fixture cannot be generated."""


def _compressed(value: bytes) -> bytes:
    return zlib.compress(value, level=9)


def _header(metadata_size: int, entry_count: int, article_offset: int) -> bytes:
    value = bytearray(44)
    value[0:4] = b"aard"
    value += struct.pack(">H", 1)
    value += bytes(16)
    value += struct.pack(">HHIII", 1, 1, metadata_size, entry_count, article_offset)
    value += b">LL\0>H>L"
    if len(value) != 86:
        raise FixtureError("Generated Aard header has the wrong size")
    return bytes(value)


def _fixture_bytes(entry_count: int) -> bytes:
    if entry_count < 1 or entry_count > MAX_ENTRY_COUNT:
        raise FixtureError("entry count is outside the supported bound")
    metadata = _compressed(
        json.dumps(
            {
                "article_language": "de",
                "description": "Generated cancellation acceptance fixture",
                "index_language": "en",
                "title": "Cancellation Fixture Aard",
            },
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
    )
    words = bytearray()
    articles = bytearray()
    word_offsets: list[int] = []
    article_offsets: list[int] = []
    for index in range(entry_count):
        word = f"entry-{index:06d}".encode("ascii")
        article_prefix = f"Definition for entry-{index:06d}; "
        article_text = article_prefix + "x" * (ARTICLE_TEXT_BYTES - len(article_prefix))
        article = _compressed(
            json.dumps(
                [article_text],
                separators=(",", ":"),
            ).encode("utf-8")
        )
        word_offsets.append(len(words))
        article_offsets.append(len(articles))
        words += struct.pack(">H", len(word)) + word
        articles += struct.pack(">I", len(article)) + article

    article_base = 86 + len(metadata) + entry_count * 8 + len(words)
    index_data = bytearray()
    for word_offset, article_record_offset in zip(
        word_offsets, article_offsets, strict=True
    ):
        index_data += struct.pack(">II", word_offset, article_record_offset)
    content = (
        _header(len(metadata), entry_count, article_base)
        + metadata
        + index_data
        + words
        + articles
    )
    if len(content) > MAX_FIXTURE_BYTES:
        raise FixtureError("Generated Aard fixture exceeds the size bound")
    return content


def generate(output: Path, entry_count: int = DEFAULT_ENTRY_COUNT) -> Path:
    output = output.resolve(strict=False)
    if output.exists():
        if output.is_symlink() or not output.is_dir() or any(output.iterdir()):
            raise FixtureError("Output must be an absent or empty directory")
    else:
        output.mkdir(parents=True)

    content = _fixture_bytes(entry_count)
    fixture = output / "fixture.aar"
    temporary: Path | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=".fixture.aar.", dir=output
        )
        temporary = Path(temporary_name)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, fixture)
        (output / DISPOSABLE_MARKER).write_text(MARKER_CONTENT, encoding="utf-8")
        (output / "PROVENANCE.txt").write_text(
            "Original synthetic GoldenDict acceptance data.\n"
            "License: GPL-3.0-or-later.\n"
            "Generated by scripts/generate_aard_cancellation_fixture.py.\n",
            encoding="utf-8",
        )
    except OSError as error:
        raise FixtureError("Cannot publish the Aard fixture") from error
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    return fixture


def main(arguments: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--entries", type=int, default=DEFAULT_ENTRY_COUNT)
    options = parser.parse_args(arguments)
    try:
        print(generate(options.output, options.entries))
    except FixtureError as error:
        print(f"error: {error}", file=os.sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
