if(WIN32)
  ti_update(TIGER_SETUPVARS_INSTALL_PATH ".")
  ti_update(TIGER_SCRIPT_EXTENSION ".cmd")
  ti_update(TIGER_SETUPVARS_TEMPLATE "setup_vars_win32.cmd.in")
else()
  ti_update(TIGER_SETUPVARS_INSTALL_PATH "bin")
  ti_update(TIGER_SCRIPT_EXTENSION ".sh")
  if(APPLE)
    ti_update(TIGER_SETUPVARS_TEMPLATE "setup_vars_macosx.sh.in")
  else()
    ti_update(TIGER_SETUPVARS_TEMPLATE "setup_vars_linux.sh.in")
  endif()
endif()

if(INSTALL_TO_MANGLED_PATHS)
  ti_update(TIGER_SETUPVARS_FILENAME "setup_vars_tiger-${TIGER_VERSION}${TIGER_SCRIPT_EXTENSION}")
else()
  ti_update(TIGER_SETUPVARS_FILENAME setup_vars_tiger5${TIGER_SCRIPT_EXTENSION})
endif()

##### build directory
if(WIN32)
  set(__build_type "${CMAKE_BUILD_TYPE}")
  if(NOT __build_type)
    set(__build_type "Release")  # default
  endif()
  file(RELATIVE_PATH TIGER_LIB_RUNTIME_DIR_RELATIVE_CMAKECONFIG "${${PROJECT_NAME}_BINARY_DIR}/" "${EXECUTABLE_OUTPUT_PATH}/${__build_type}/")
else()
  file(RELATIVE_PATH TIGER_LIB_RUNTIME_DIR_RELATIVE_CMAKECONFIG "${${PROJECT_NAME}_BINARY_DIR}/" "${LIBRARY_OUTPUT_PATH}/")
endif()
set(TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG "python_loader") 
configure_file("${${PROJECT_NAME}_SOURCE_DIR}/cmake/templates/${TIGER_SETUPVARS_TEMPLATE}" "${CMAKE_BINARY_DIR}/tmp/setup_vars${TIGER_SCRIPT_EXTENSION}" @ONLY)
file(COPY "${CMAKE_BINARY_DIR}/tmp/setup_vars${TIGER_SCRIPT_EXTENSION}" DESTINATION "${CMAKE_BINARY_DIR}"
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

##### install directory
if(WIN32)
  file(RELATIVE_PATH TIGER_LIB_RUNTIME_DIR_RELATIVE_CMAKECONFIG
      "${CMAKE_INSTALL_PREFIX}/${TIGER_SETUPVARS_INSTALL_PATH}/" "${CMAKE_INSTALL_PREFIX}/${TIGER_BIN_INSTALL_PATH}/")
else()
  file(RELATIVE_PATH TIGER_LIB_RUNTIME_DIR_RELATIVE_CMAKECONFIG
      "${CMAKE_INSTALL_PREFIX}/${TIGER_SETUPVARS_INSTALL_PATH}/" "${CMAKE_INSTALL_PREFIX}/${TIGER_LIB_INSTALL_PATH}/")
endif()
file(RELATIVE_PATH TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG
    "${CMAKE_INSTALL_PREFIX}/${TIGER_SETUPVARS_INSTALL_PATH}/" "${CMAKE_INSTALL_PREFIX}/")
if(DEFINED TIGER_PYTHON_INSTALL_PATH)
  set(__python_path "${TIGER_PYTHON_INSTALL_PATH}")
elseif(DEFINED TIGER_PYTHON_INSTALL_PATH_SETUPVARS)
  set(__python_path "${TIGER_PYTHON_INSTALL_PATH_SETUPVARS}")
endif()
if(DEFINED __python_path)
  if(IS_ABSOLUTE "${__python_path}")
    set(TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG "${__python_path}")
    message(WARNING "CONFIGURATION IS NOT SUPPORTED: validate setupvars script in install directory")
  else()
    ti_path_join(TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG "${TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG}" "${__python_path}")
  endif()
else()
  if(DEFINED TIGER_PYTHON3_INSTALL_PATH)
    ti_path_join(TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG "${TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG}" "${TIGER_PYTHON3_INSTALL_PATH}")
  else()
    set(TIGER_PYTHON_DIR_RELATIVE_CMAKECONFIG "python_loader_is_not_installed")
  endif()
endif()
configure_file("${${PROJECT_NAME}_SOURCE_DIR}/cmake/templates/${TIGER_SETUPVARS_TEMPLATE}" "${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/install/${TIGER_SETUPVARS_FILENAME}" @ONLY)
install(FILES "${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/install/${TIGER_SETUPVARS_FILENAME}"
    DESTINATION "${TIGER_SETUPVARS_INSTALL_PATH}"
    PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
    COMPONENT scripts)
