SET(TIGER_VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/modules/base/include/tiger/base/version.hpp")
file(STRINGS "${TIGER_VERSION_FILE}" TIGER_VERSION_PARTS REGEX "#define TI_VERSION_[A-Z]+[ ]+" )

string(REGEX REPLACE ".+TI_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" TIGER_VERSION_MAJOR "${TIGER_VERSION_PARTS}")
string(REGEX REPLACE ".+TI_VERSION_MINOR[ ]+([0-9]+).*" "\\1" TIGER_VERSION_MINOR "${TIGER_VERSION_PARTS}")
string(REGEX REPLACE ".+TI_VERSION_REVISION[ ]+([0-9]+).*" "\\1" TIGER_VERSION_PATCH "${TIGER_VERSION_PARTS}")
string(REGEX REPLACE ".+TI_VERSION_STATUS[ ]+\"([^\"]*)\".*" "\\1" TIGER_VERSION_STATUS "${TIGER_VERSION_PARTS}")

set(TIGER_VERSION_PLAIN "${TIGER_VERSION_MAJOR}.${TIGER_VERSION_MINOR}.${TIGER_VERSION_PATCH}")

set(TIGER_VERSION "${TIGER_VERSION_PLAIN}${TIGER_VERSION_STATUS}")

set(TIGER_SOVERSION "${TIGER_VERSION_MAJOR}.${TIGER_VERSION_MINOR}")
set(TIGER_LIBVERSION "${TIGER_VERSION_MAJOR}.${TIGER_VERSION_MINOR}.${TIGER_VERSION_PATCH}")

# create a dependency on the version file
# we never use the output of the following command but cmake will rerun automatically if the version file changes
configure_file("${TIGER_VERSION_FILE}" "${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/tiger_junk/version.junk" COPYONLY)

ti_update(TIGER_VS_VER_FILEVERSION_QUAD "${TIGER_VERSION_MAJOR},${TIGER_VERSION_MINOR},${TIGER_VERSION_PATCH},0")
ti_update(TIGER_VS_VER_PRODUCTVERSION_QUAD "${TIGER_VERSION_MAJOR},${TIGER_VERSION_MINOR},${TIGER_VERSION_PATCH},0")
ti_update(TIGER_VS_VER_FILEVERSION_STR "${TIGER_VERSION}")
ti_update(TIGER_VS_VER_PRODUCTVERSION_STR "${TIGER_VERSION}")
ti_update(TIGER_VS_VER_PRODUCTNAME_STR "Tiger Platform")
ti_update(TIGER_VS_VER_COMMENTS_STR "http://www.shlaser.com/")
